// Greedy heuristic fallback — runs when there's no Anthropic key (or AI call fails).
// Produces the SAME CoverageSuggestionOutput shape as the AI call → flows through the identical
// buildSuggestionDraft validator. Labeled source:'heuristic' so the banner never misrepresents it.
// Plans/tech/3b-coverage-suggestions.md §3.4.
import type { CoverageSuggestionOutput } from '@/lib/ai/schemas';
import type { SuggestionEngineInput } from '@/lib/types';

function overlaps(
  aStart: string | null, aEnd: string | null,
  bStart: string | null, bEnd: string | null,
): boolean {
  if (!aStart || !aEnd || !bStart || !bEnd) return false;
  return aStart <= bEnd && bStart <= aEnd;
}

export function heuristicSuggestion(ctx: SuggestionEngineInput): CoverageSuggestionOutput {
  const today = new Date().toISOString().split('T')[0];
  const committedPairs = new Set(ctx.committed.map((c) => `${c.repId}|${c.conferenceId}`));

  // Upcoming, non-committed, plannable conferences sorted by tier (T1 first), then ICP score desc.
  const upcoming = ctx.conferences
    .filter((c) => (!c.endDate || c.endDate >= today) && !ctx.committed.some((cm) => cm.conferenceId === c.id))
    .sort((a, b) => {
      const tierOrd = (t: string | null) => (t === 'T1' ? 0 : t === 'T2' ? 1 : 2);
      const td = tierOrd(a.tier) - tierOrd(b.tier);
      return td !== 0 ? td : (b.icpScore ?? 0) - (a.icpScore ?? 0);
    });

  // Track assignments and booked intervals per rep.
  const repLoad = new Map<string, number>(ctx.reps.map((r) => [r.id, 0]));
  const repIntervals = new Map<string, { start: string; end: string }[]>(ctx.reps.map((r) => [r.id, []]));

  // Seed rep intervals from committed coverage.
  for (const { repId, conferenceId } of ctx.committed) {
    const conf = ctx.conferences.find((c) => c.id === conferenceId);
    if (conf?.startDate && conf.endDate) {
      repIntervals.get(repId)?.push({ start: conf.startDate, end: conf.endDate });
    }
    repLoad.set(repId, (repLoad.get(repId) ?? 0) + 1);
  }

  const assignments: CoverageSuggestionOutput['assignments'] = [];

  for (const conf of upcoming) {
    // Eligible reps: under capacity, no double-booking with this event.
    const eligible = ctx.reps.filter((r) => {
      if ((repLoad.get(r.id) ?? 0) >= r.capacity) return false;
      if (committedPairs.has(`${r.id}|${conf.id}`)) return false;
      const existing = repIntervals.get(r.id) ?? [];
      return !existing.some((iv) => overlaps(conf.startDate, conf.endDate, iv.start, iv.end));
    });
    if (eligible.length === 0) continue;

    // Prefer a rep whose homeRegion matches the conference region; break ties by least loaded.
    const regionMatch = eligible.filter((r) => r.homeRegion && r.homeRegion === conf.region);
    const pool = regionMatch.length > 0 ? regionMatch : eligible;
    const chosen = pool.reduce((best, r) =>
      (repLoad.get(r.id) ?? 0) < (repLoad.get(best.id) ?? 0) ? r : best,
    );

    assignments.push({ repId: chosen.id, conferenceId: conf.id, reason: `Greedy: ${chosen.homeRegion === conf.region ? 'home region match' : 'least loaded'}` });
    repLoad.set(chosen.id, (repLoad.get(chosen.id) ?? 0) + 1);
    if (conf.startDate && conf.endDate) {
      repIntervals.get(chosen.id)?.push({ start: conf.startDate, end: conf.endDate });
    }
    committedPairs.add(`${chosen.id}|${conf.id}`);
  }

  return {
    assignments,
    perRepNotes: ctx.reps.map((r) => ({
      repId: r.id,
      note: `Assigned ${assignments.filter((a) => a.repId === r.id).length} conference(s) by heuristic.`,
    })),
    rationale:
      'This plan was generated by a deterministic heuristic (no AI key configured). ' +
      'T1 events are covered first (ICP score desc), then T2. ' +
      'Each event is assigned to the eligible rep whose home region matches, falling back to the least-loaded rep. ' +
      'Add an Anthropic key in Settings to generate an AI-optimized suggestion.',
    unsatisfiable: [],
  };
}
